git: docker/uic-resources: Removed as not part of UnifyCore (LFS)
This change is motivated by zeal project

Tests are passing, but it fail later on installing package:

  #12 1.646 dpkg: error processing archive ./build/z-wave-protocol-controller_1.7.0_x86_64/libunify_1.7.0-65-gbc86741e_x86_64.deb (--install):
  Error: No space left on device : '/home/runner/runners/2.323.0/_diag/pages/a643bedf-49e7-4c3e-9568-b498945dda79_dd23db01-cff6-57a4-373a-5c8097a97333_1.log'

I suspect the cause it all the assets in tree, this has to be cleaned up.

This change prevent this problem, further cleaning may be considered.

Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/11#issuecomment-2748887134
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-protocol-controller/issues/77
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/10
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/11
Relate-to: https://github.com/SiliconLabsSoftware/z-wave-engine-application-layer/issues/7
Signed-off-by: Philippe Coval <philippe.coval@silabs.com>